plugins {
    id 'com.android.application'
}
android {
    namespace 'com.vpr.server'
    compileSdk 34
    defaultConfig {
        applicationId "com.vpr.server"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "3.0"
        multiDexEnabled true
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt',
                'META-INF/*.SF',
                'META-INF/*.DSA',
                'META-INF/*.RSA',
                'META-INF/versions/**',
                'mozilla/public-suffix-list.txt'
            ]
        }
    }
}
configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.2'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'org.mozilla:rhino:1.7.14'
    implementation 'org.python:jython-standalone:2.7.3'
}
